
library(readxl)
library(dplyr)
library(lubridate)
library(dynlm)
library(ggplot2)
library(tseries)
library(prophet)
library(forecast)
library(stringr)
library(data.table)
library(zoo)
setwd("/Users/vishwasdhanda/Desktop/heltcare_project/forecasting")
full = read_excel('TVlift.xlsx')
full

#day of the week seasonality (dow) for fit02, fit04
full$dow = wday(full$date)
train = full[1:334,]
full_ts = ts(full$sales, frequency=1, start=c(min(full$date),1))
train_ts = ts(train$sales, frequency=1, start=c(min(train$date),1))
ts.plot(train_ts)


#Models
fit01 = lm(sales ~ sb + snb + tv, data=train)
fit02 = lm(sales ~ sb + snb + tv + factor(dow), data=train) 
fit03 = lm(sales ~ lag(sales,1) + sb + snb + tv, data=train)
fit04 = lm(sales ~ lag(sales,1) + sb + snb + tv + factor(dow), data=train)
fit05 = auto.arima(train$sales, xreg = cbind(train$sb, train$snb, train$tv))

# Initialize an empty data frame called 'results_df' with columns 'model_name' and 'testing_data'
results_df = data.frame(matrix(ncol=2, nrow=0))
colnames(results_df) = c('model_name', 'RMSE_test')

# Create an empty list to store forecasts
forecasts = c()

# Iterate through four distinct models - fit01, fit02, fit03, fit04
for (model_number in 1:4) {
  # Generate a unique name for the forecast variable
  forecast_variable = paste0('predict_', str_pad(model_number, 2, pad="0"), sep="")
  
  # Retrieve the specific model associated with the current iteration
  selected_model = get(paste0('fit', str_pad(model_number, 2, pad="0")))
  
  # Generate forecasts using the selected model on the entire dataset
  full[[forecast_variable]] = predict(selected_model, newdata=full)
  
  # Convert the forecasts into time series format and store them in the 'forecasts' list
  forecasts[[forecast_variable]] = ts(full[[forecast_variable]], frequency=1, start=c(min(full$date), 1))
  
  # Create a time series plot comparing the entire dataset with the forecasts
  ts.plot(full_ts, forecasts[[forecast_variable]], col = c("black", "blue"))
  
  # Create a subset of the full dataset for testing purposes
  test = full[335:353,]
  
  # Convert the test dataset into a time series
  test_ts = ts(test$sales, frequency=1, start=c(min(test$date),1))
  
  # Create a time series plot comparing the testing dataset with the forecasts generated by the specific model
  ts.plot(test_ts, forecasts[[forecast_variable]][335:353], col = c("black", "blue"))
  
  # Calculate the root mean squared error (RMSE) and include it in the 'results_df'
  results_df = rbindlist(list(results_df, as.list(c(model_number, sqrt(mean((test[[forecast_variable]] - test$sales)^2))))))
}

#Model - fit05
train$predict_05 = predict(fit05, newxreg=cbind(train$sb, train$snb, train$tv))$pred
test$predict_05 = predict(fit05, newxreg=cbind(test$sb, test$snb, test$tv))$pred
full$predict_05= predict(fit05, newxreg=cbind(full$sb, full$snb, full$tv))$pred
forecasts$predict_05 = ts(full$predict_05, frequency=1, start=c(min(full$date),1))
ts.plot(full_ts, forecasts$predict_05, col = c("black","blue"))

test = full[335:353,]
test_ts = ts(test$sales, frequency=1, start=c(min(test$date),1))
ts.plot(test_ts, forecasts$predict_05[335:353], col = c("black","blue"))
results_df = rbindlist(list(results_df, as.list(c(5, sqrt(mean((test$predict_05-test$sales)^2))))))
checkresiduals(fit05)

# Let's try some more simple models - fit 06, fit07, fit08, fit09 
# as it's stated that simple model as a better RMSE ( Additional Note)
fit06 = dynlm(sales ~ lag(sales,1), data=train)
fit07 = dynlm(sales ~ sb, data=train)
fit08 = dynlm(sales ~ snb, data=train)
fit09 = dynlm(sales ~ tv, data=train)

for (model_number in 6:9) {
  forecast_variable = paste0('predict_', str_pad(model_number, 2, pad="0"), sep="")
  selected_model = get(paste0('fit', str_pad(model_number, 2, pad="0")))
  full[[forecast_variable]] = predict(selected_model, newdata=full)
  forecasts[[forecast_variable]] = ts(full[[forecast_variable]], frequency=1, start=c(min(full$date), 1))
  ts.plot(full_ts, forecasts[[forecast_variable]], col = c("black", "blue"))
  test = full[335:353,]
  test_ts = ts(test$sales, frequency=1, start=c(min(test$date),1))
  ts.plot(test_ts, forecasts[[forecast_variable]][335:353], col = c("black", "blue"))
  results_df = rbindlist(list(results_df, as.list(c(model_number, sqrt(mean((test[[forecast_variable]] - test$sales)^2))))))
}

# Let's try some more complex linear models - fit 10, fit11, fit12, fit13
fit10 = dynlm(sales ~ lag(sales,1) + lag(sb,1) + lag(snb,1) + lag(tv,1) + factor(dow), data=train)
fit11 = dynlm(sales ~ lag(sales,1) + lag(sb,1) + lag(snb,1) + lag(tv,1) + factor(dow)
              + (lag(sales,1) + lag(sb, 1) + lag(snb, 1) + lag(tv, 1))^2, data=train)
fit12 = dynlm(sales ~ lag(sales,1) + lag(sb,1) + lag(snb,1) + lag(tv,1) + factor(dow)
              + lag(sales,7) + lag(sb,7) + lag(snb,7) + lag(tv,7)
              + (lag(sales,1) + lag(sb, 1) + lag(snb, 1) + lag(tv, 1))^2
              + (lag(sales,7) + lag(sb, 7) + lag(snb, 7) + lag(tv, 7))^2, data=train)
fit13 = dynlm(sales ~ lag(sales,1) + lag(sb,1) + lag(snb,1) + lag(tv,1) + factor(dow)
              + lag(sales,30) + lag(sb,30) + lag(snb,30) + lag(tv,30)
              + (lag(sales,1) + lag(sb, 1) + lag(snb, 1) + lag(tv, 1))^2
              + (lag(sales,30) + lag(sb, 30) + lag(snb, 30) + lag(tv, 30))^2, data=train)


for (model_number in 10:13) {
  forecast_variable = paste0('predict_', str_pad(model_number, 2, pad="0"), sep="")
  selected_model = get(paste0('fit', str_pad(model_number, 2, pad="0")))
  full[[forecast_variable]] = predict(selected_model, newdata=full)
  forecasts[[forecast_variable]] = ts(full[[forecast_variable]], frequency=1, start=c(min(full$date), 1))
  ts.plot(full_ts, forecasts[[forecast_variable]], col = c("black", "blue"))
  test = full[335:353,]
  test_ts = ts(test$sales, frequency=1, start=c(min(test$date),1))
  ts.plot(test_ts, forecasts[[forecast_variable]][335:353], col = c("black", "blue"))
  results_df = rbindlist(list(results_df, as.list(c(model_number, sqrt(mean((test[[forecast_variable]] - test$sales)^2))))))
}

results_df
for (i in 1:13) {
  cat("\nModel", i, "summary:\n")
  selected_model <- get(paste0('fit', str_pad(i, 2, pad = "0")))
  print(summary(selected_model))
  cat("\nSignificant Variables (p < 0.05):\n")
  sig_vars <- summary(selected_model)$coefficients[, 4] < 0.05
  print(names(sig_vars)[sig_vars])
}
